CREATE DATABASE IF NOT EXISTS `PROCUREMENT` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `PROCUREMENT`;

CREATE TABLE IF NOT EXISTS `accounts` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(100) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` VARCHAR(20) NOT NULL DEFAULT 'user',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `products` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `category` VARCHAR(100) NOT NULL,
  `brand` VARCHAR(100) NOT NULL,
  `item_name` VARCHAR(255) NOT NULL,
  `model` VARCHAR(255) DEFAULT '',
  `specs` JSON DEFAULT NULL,
  `unit` VARCHAR(50) DEFAULT 'Each',
  `unit_cost` DECIMAL(12,2) DEFAULT 0.00,
  `latest_price` DECIMAL(12,2) DEFAULT NULL,
  `price_source` VARCHAR(255) DEFAULT NULL,
  `price_url` VARCHAR(500) DEFAULT NULL,
  `abc_class` CHAR(1) NOT NULL DEFAULT 'C',
  `source` VARCHAR(150) DEFAULT '',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_price_updated` TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY `unique_product` (`category`, `brand`, `model`, `item_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
